theme: jekyll-theme-minimal
title: My Title
description: My description
url: https://dlodola.github.io/public/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Domenico Lodola
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
