theme: jekyll-theme-minimal
title: My Title
description: A small collection of python tricks & tools for geologists, with a focus on oil & gas.
url: https://dlodola.github.io/public/
repository: public
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Domenico Lodola
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
