theme: jekyll-theme-minimal
title: skylark geoscience
description: A collection of Python tricks & tools for geologists, with a focus on oil & gas.
url: https://dlodola.github.io/public/
repository: public
logo: logo.png
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Domenico Lodola
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
